[theme]
base = "light"
primaryColor = "#1f6f78"
backgroundColor = "#F5F3EE"
secondaryBackgroundColor = "#ECE6D8"
textColor = "#2A2A28"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
